"""empty message

Revision ID: fc57080cc7bf
Revises: 22d9fa2f7d49
Create Date: 2025-01-24 02:13:46.238871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc57080cc7bf'
down_revision: Union[str, None] = '22d9fa2f7d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investments', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investments', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
